"use client";

import { ChevronDown, Minus, Plus } from "lucide-react";
import { useState } from "react";

export function DarkHomeFaq() {
  const [openIndex, setOpenIndex] = useState(-1);
  return (
    <section className="mx-auto w-full max-w-[40rem] space-y-6">
      <h2 className="text-center text-2xl font-bold leading-tight tracking-[-0.02em] text-white sm:text-3xl">
        FAQ
      </h2>
      <div className="space-y-2.5 sm:space-y-3">
        {faqItems.map((item, index) => {
          const isOpen = openIndex === index;
          return (
            <div key={item.question} className="glass-panel overflow-hidden rounded-none">
              <button
                type="button"
                className={`flex w-full cursor-pointer items-center justify-between gap-4 px-5 py-3.5 text-left transition-colors sm:px-6 sm:py-4 ${isOpen ? "" : "hover:bg-[#27272a]"}`}
                aria-expanded={isOpen}
                onClick={() => setOpenIndex(isOpen ? -1 : index)}
              >
                <span className="text-[13px] font-bold leading-5 text-white sm:text-sm sm:leading-6">{item.question}</span>
                <ChevronDown
                  size={16}
                  strokeWidth={2}
                  className="text-[#90909a] shrink-0 transition-transform duration-200"
                  style={{ transform: isOpen ? "rotate(180deg)" : "rotate(0deg)" }}
                />
              </button>
              {isOpen && (
                <div className="px-5 pb-4 pt-0 sm:px-6 sm:pb-5">
                  <p className="text-[13px] leading-6 text-[#c6c5d0] sm:text-sm sm:leading-7">{item.answer}</p>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}

const faqItems = [
  {
    question: "What does Metric's AI analysis actually cover?",
    answer:
      "Every analysis pulls the current price, day move, 52-week range position, trading volume, key fundamentals like P/E and profit margins, peer comparison, recent news, and technical signals. Claude (Anthropic's AI model) reads all of it together and writes a plain-English brief so you know what the data actually means before you act.",
  },
  {
    question: "Does Metric give buy or sell recommendations?",
    answer:
      "No, and that is by design. Metric explains what the data is saying. It does not tell you what to do with it. You will never see a buy rating, target price, or stop loss. We give you the clearest possible read of the facts so the decision stays yours.",
  },
  {
    question: "Where does Metric get its stock data?",
    answer:
      "Live market prices and fundamentals come from Upstox and Yahoo Finance. News sentiment and technical signals are sourced through Tradient. The written analysis is generated by Claude AI. Pulling from multiple providers means you get a more complete picture than any single data feed.",
  },
  {
    question: "How real-time is the stock analysis?",
    answer:
      "Market prices update with each new analysis you run. Fundamentals refresh when the data providers push new filings, which typically happens each quarter. Every report shows the exact timestamp of the data it was built on, so you always know how fresh the numbers are.",
  },
  {
    question: "Can I search by company name instead of the stock ticker?",
    answer:
      "Yes. Type the company name like HDFC Bank, Tata Motors, or Infosys and Metric finds the right NSE or BSE listing automatically. You can also enter the ticker directly if you know it. Either approach works the same way.",
  },
];

export function HomeFaq() {
  const [openIndex, setOpenIndex] = useState(-1);

  return (
    <section className="animate-entrance delay-4 surface p-4">
      <div className="mb-3 flex items-center justify-between gap-3">
        <h2
          className="text-[25px] leading-none text-black [text-shadow:0.45px_0_0_#000,-0.45px_0_0_#000]"
          style={{ fontFamily: 'Georgia, "Times New Roman", Times, serif', fontWeight: 700 }}
        >
          Questions, answered
        </h2>
        <span className="border-2 border-black bg-metric-finance-accent-soft px-2 py-1 font-mono text-[9px] font-black uppercase tracking-[0.08em] text-metric-blue">
          FAQ
        </span>
      </div>

      <div className="grid gap-2">
        {faqItems.map((item, index) => {
          const isOpen = openIndex === index;
          return (
            <div key={item.question} className="overflow-hidden border-2 border-black bg-white">
              <button
                type="button"
                className="faq-trigger flex w-full items-center justify-between gap-4 px-3 py-3 text-left"
                aria-expanded={isOpen}
                onClick={() => setOpenIndex(isOpen ? -1 : index)}
              >
                <span className="font-mono text-sm font-black leading-5 tracking-[0.02em] text-black">
                  {item.question}
                </span>
                <span className="neo-press flex h-7 w-7 shrink-0 items-center justify-center border-2 border-black bg-metric-finance-accent-soft">
                  {isOpen ? <Minus size={16} strokeWidth={2.8} /> : <Plus size={16} strokeWidth={2.8} />}
                </span>
              </button>
              <div className={`faq-answer ${isOpen ? "faq-answer-open" : ""}`}>
                <p className="border-t-2 border-black px-3 pb-4 pt-3 text-sm font-medium leading-6 text-metric-muted">
                  {item.answer}
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
