// Plain English glossary. Written like you're 5, never advice. No dashes anywhere in this content.
export type Term = {
  slug: string;
  term: string;
  simple: string;
  explain: string;
  example: string;
  why: string;
  related: string[];
};

export const TERMS: Term[] = [
  { slug: "market-cap", term: "Market cap", simple: "Market cap is the price tag of a whole company on the stock market.",
    explain: "Market capitalization is the share price multiplied by the number of shares that exist. It tells you how big the market thinks a company is. Companies are often grouped as large cap, mid cap or small cap depending on this number.",
    example: "If a company has 1 billion shares and each share costs 50 dollars, its market cap is 50 billion dollars.",
    why: "Market cap is a better way to compare company size than share price. A 20 dollar stock can be a giant and a 500 dollar stock can be tiny.", related: ["share-price", "large-cap-stock", "pe-ratio"] },
  { slug: "pe-ratio", term: "P/E ratio", simple: "The P/E ratio shows how many dollars people pay for each dollar a company earns in a year.",
    explain: "P/E stands for price to earnings. You divide the share price by the company's earnings per share. A high P/E usually means investors expect strong growth. A low P/E can mean slower growth or a bargain, so it needs context.",
    example: "A stock priced at 100 dollars that earns 5 dollars per share has a P/E ratio of 20.",
    why: "It is one quick way to see if a stock is priced richly or cheaply compared with similar companies.", related: ["eps", "growth-stock", "value-stock"] },
  { slug: "eps", term: "EPS (earnings per share)", simple: "EPS is how much profit a company made for each share of its stock.",
    explain: "Earnings per share is net profit divided by the number of shares. Companies report it every quarter. Investors compare it with what analysts expected, and the gap often moves the stock.",
    example: "A company that earns 2 billion dollars with 1 billion shares has an EPS of 2 dollars.",
    why: "EPS is the number most headlines mean when they say a company beat or missed expectations.", related: ["earnings-report", "pe-ratio", "guidance"] },
  { slug: "dividend", term: "Dividend", simple: "A dividend is a thank you payment some companies send to the people who own their stock.",
    explain: "When a company makes more cash than it needs, it may share part of it with shareholders. Dividends are usually paid every quarter. Not every company pays one, and a company can raise, cut or stop its dividend.",
    example: "If a company pays 1 dollar per share each year and you own 100 shares, you receive 100 dollars a year.",
    why: "Dividends are a way to earn money from a stock without selling it.", related: ["dividend-yield", "value-stock", "blue-chip-stock"] },
  { slug: "dividend-yield", term: "Dividend yield", simple: "Dividend yield tells you how much a stock pays each year compared with its price.",
    explain: "You divide the yearly dividend per share by the share price. A higher yield means more cash for each dollar invested, but a very high yield can be a warning sign that the price has dropped or the dividend is at risk.",
    example: "A 100 dollar stock that pays 3 dollars a year has a dividend yield of 3 percent.",
    why: "It helps you compare income from different stocks on the same scale.", related: ["dividend", "share-price", "pe-ratio"] },
  { slug: "earnings-report", term: "Earnings report", simple: "An earnings report is a company's report card, published four times a year.",
    explain: "Public companies share how much they sold, how much they earned and what they expect next. These reports come out every quarter and are among the biggest moments for a stock, because prices can move sharply when results surprise investors.",
    example: "A company reports sales of 10 billion dollars when analysts expected 9.5 billion. The stock may jump.",
    why: "Many large daily stock moves happen right after an earnings report.", related: ["eps", "revenue", "guidance"] },
  { slug: "revenue", term: "Revenue", simple: "Revenue is all the money a company brings in from selling things, before paying any costs.",
    explain: "Revenue is also called sales or the top line. It shows how big the business is and whether it is growing. Profit is what is left after costs, so a company can have high revenue and still lose money.",
    example: "A coffee chain that sells 1 billion dollars of coffee has 1 billion dollars of revenue, even if its profit is much smaller.",
    why: "Growing revenue is one of the clearest signs a business is gaining customers.", related: ["profit-margin", "earnings-report", "eps"] },
  { slug: "profit-margin", term: "Profit margin", simple: "Profit margin shows how many cents of profit a company keeps from every dollar it sells.",
    explain: "You divide profit by revenue. A 20 percent margin means the company keeps 20 cents of each dollar of sales. Software companies often have high margins, while grocery stores usually have low ones.",
    example: "A company with 100 dollars of sales and 15 dollars of profit has a 15 percent profit margin.",
    why: "Margins show how efficient a business is and how much room it has to absorb higher costs.", related: ["revenue", "eps", "free-cash-flow"] },
  { slug: "free-cash-flow", term: "Free cash flow", simple: "Free cash flow is the cash a company has left after paying to run and grow the business.",
    explain: "It is the cash from operations minus spending on equipment and buildings. Free cash flow can be used to pay dividends, buy back shares, pay down debt or invest in new projects.",
    example: "A company earns 10 billion in cash and spends 3 billion on factories. Its free cash flow is 7 billion.",
    why: "It is harder to fake than profit, so many investors watch it closely.", related: ["profit-margin", "dividend", "stock-buyback"] },
  { slug: "stock-buyback", term: "Stock buyback", simple: "A buyback is when a company buys its own shares from the market.",
    explain: "When a company buys back shares, there are fewer shares left. Each remaining share then owns a slightly bigger slice of the company, which can lift earnings per share.",
    example: "A company spends 5 billion dollars buying its own stock instead of paying it out as a dividend.",
    why: "Buybacks are another way companies return cash to shareholders.", related: ["dividend", "free-cash-flow", "eps"] },
  { slug: "guidance", term: "Guidance", simple: "Guidance is a company's own prediction of how it will do in the future.",
    explain: "Along with the report card, many companies tell investors what sales and profit they expect next quarter or year. Guidance that is higher or lower than analysts expect can move a stock more than the results themselves.",
    example: "A company beats this quarter's numbers but says next quarter will be weak. The stock may fall anyway.",
    why: "Markets look forward, so what a company says about the future often matters more than the past.", related: ["earnings-report", "eps", "analyst-rating"] },
  { slug: "stock-split", term: "Stock split", simple: "A stock split cuts one share into several smaller shares, like cutting a pizza into more slices.",
    explain: "In a split, a company gives each shareholder more shares and lowers the price per share so that the total value stays the same. Companies split to make shares look more affordable.",
    example: "In a 2 for 1 split, 1 share worth 200 dollars becomes 2 shares worth 100 dollars each.",
    why: "A split does not change what a company is worth, but it can bring more attention and buyers.", related: ["share-price", "market-cap", "stock-ticker"] },
  { slug: "share-price", term: "Share price", simple: "The share price is what one slice of a company costs right now.",
    explain: "Prices change throughout the trading day as buyers and sellers agree on deals. A higher price per share does not mean a bigger or better company, only that each slice is priced higher.",
    example: "If a share costs 150 dollars, buying 2 shares costs 300 dollars.",
    why: "Share price is the number everyone sees, but it needs market cap and context to mean anything.", related: ["market-cap", "stock-split", "volume"] },
  { slug: "stock-ticker", term: "Stock ticker", simple: "A ticker is a short nickname, usually 1 to 5 letters, that identifies a stock.",
    explain: "Every public company has a unique ticker on its exchange. For example, Apple is AAPL and Microsoft is MSFT. You use the ticker to look up a stock or place an order.",
    example: "Searching AAPL brings up Apple's stock, not a random company.",
    why: "Tickers are the quickest way to find the exact stock you mean.", related: ["share-price", "stock-exchange", "market-cap"] },
  { slug: "stock-exchange", term: "Stock exchange", simple: "A stock exchange is a marketplace where people buy and sell shares of companies.",
    explain: "The two biggest in the United States are the New York Stock Exchange and the Nasdaq. A company lists its shares on one of them so the public can trade. Regular trading runs from 9:30 AM to 4 PM Eastern time on weekdays.",
    example: "Tesla shares trade on the Nasdaq, while Coca Cola shares trade on the New York Stock Exchange.",
    why: "The exchange sets the hours and rules for when a stock can be traded.", related: ["stock-ticker", "volume", "market-order"] },
  { slug: "bull-market", term: "Bull market", simple: "A bull market is a long stretch when stock prices mostly go up and people feel confident.",
    explain: "Analysts often say a bull market begins after prices rise about 20 percent from a recent low. During one, jobs and company profits are usually growing and investors are optimistic.",
    example: "Stocks rise for two years in a row and most investors are making money. That is a bull market.",
    why: "Knowing which phase the market is in helps you understand the mood behind daily moves.", related: ["bear-market", "volatility", "market-correction"] },
  { slug: "bear-market", term: "Bear market", simple: "A bear market is a long stretch when stock prices keep falling and people feel worried.",
    explain: "A bear market is usually defined as a drop of 20 percent or more from a recent high. They often happen alongside slowing economies. Historically they have ended and stock prices have recovered, though timing is never certain.",
    example: "An index falls 25 percent over six months as companies report weaker profits.",
    why: "Bear markets test patience, and understanding them helps avoid panic decisions.", related: ["bull-market", "market-correction", "volatility"] },
  { slug: "market-correction", term: "Market correction", simple: "A correction is a sudden drop of about 10 percent from a recent high.",
    explain: "Corrections are fairly common and often happen when prices have risen quickly. They are smaller than a bear market and are sometimes seen as a reset after a big run.",
    example: "The S&P 500 falls 10 percent over a few weeks and then stabilizes.",
    why: "Corrections feel scary, but they are a normal part of how markets move.", related: ["bear-market", "bull-market", "volatility"] },
  { slug: "volatility", term: "Volatility", simple: "Volatility is how bumpy a stock's price ride is.",
    explain: "A volatile stock swings up and down a lot, sometimes in a single day. A calm stock moves slowly. Higher volatility means bigger possible gains and bigger possible losses.",
    example: "A stock that moves 5 percent most days is more volatile than one that moves half a percent.",
    why: "Knowing how bumpy a stock is helps you decide whether you can stomach its ride.", related: ["beta", "bear-market", "diversification"] },
  { slug: "beta", term: "Beta", simple: "Beta tells you whether a stock tends to swing more or less than the overall market.",
    explain: "A beta of 1 means the stock moves about like the market. Above 1 means it swings more, below 1 means it swings less. It looks at the past, so it is only a rough guide.",
    example: "A stock with a beta of 1.5 might rise 15 percent when the market rises 10 percent, and fall by a similar extra amount.",
    why: "It is a quick way to see how risky a stock is compared with the market.", related: ["volatility", "s-and-p-500", "diversification"] },
  { slug: "volume", term: "Trading volume", simple: "Volume is how many shares changed hands in a day.",
    explain: "High volume means lots of people are trading a stock, often because of news. Low volume means little interest. A price move on high volume is usually seen as more meaningful than one on low volume.",
    example: "A stock that normally trades 5 million shares a day jumps to 30 million after an earnings report.",
    why: "Volume shows how much attention a price move is getting.", related: ["share-price", "stock-exchange", "bid-ask-spread"] },
  { slug: "bid-ask-spread", term: "Bid ask spread", simple: "The spread is the small gap between what buyers offer and what sellers ask.",
    explain: "The bid is the highest price a buyer will pay and the ask is the lowest price a seller will accept. Popular stocks have tiny spreads. Rarely traded ones have wider spreads, which makes them costlier to trade.",
    example: "Buyers bid 99.98 dollars and sellers ask 100.02 dollars. The spread is 4 cents.",
    why: "A wide spread is a hidden cost when you buy or sell.", related: ["market-order", "limit-order", "volume"] },
  { slug: "market-order", term: "Market order", simple: "A market order means buy or sell right now at whatever the current price is.",
    explain: "It is fast and almost always gets filled, but the exact price can differ slightly from what you saw, especially in fast moving or thinly traded stocks.",
    example: "You place a market order for 10 shares and they are bought immediately at the best available price.",
    why: "It is the simplest way to trade when speed matters more than the exact price.", related: ["limit-order", "bid-ask-spread", "stock-exchange"] },
  { slug: "limit-order", term: "Limit order", simple: "A limit order says buy or sell only if the price reaches the number I choose.",
    explain: "You set the highest price you will pay or the lowest price you will accept. The trade only happens at that price or better, so it gives control but might never get filled.",
    example: "You set a limit order to buy at 48 dollars. If the stock never falls to 48, nothing happens.",
    why: "It protects you from paying more than you intended.", related: ["market-order", "bid-ask-spread", "share-price"] },
  { slug: "etf", term: "ETF (exchange traded fund)", simple: "An ETF is a basket of many investments that you can buy in one click, like a stock.",
    explain: "An ETF holds lots of stocks, bonds or other assets and trades on an exchange all day. Many follow an index. Owning one gives you a small piece of everything in the basket.",
    example: "An ETF that follows the S&P 500 gives you a slice of 500 large companies in one purchase.",
    why: "ETFs make it easy to spread your money across many companies at once.", related: ["index-fund", "diversification", "s-and-p-500"] },
  { slug: "index-fund", term: "Index fund", simple: "An index fund copies a list of companies instead of trying to pick winners.",
    explain: "It buys the same stocks as an index, in the same proportions. Because nobody is picking stocks, fees are usually low. Index funds can be mutual funds or ETFs.",
    example: "An S&P 500 index fund holds the same 500 companies as the S&P 500.",
    why: "They are a popular, low cost way to follow the whole market.", related: ["etf", "s-and-p-500", "diversification"] },
  { slug: "s-and-p-500", term: "S&P 500", simple: "The S&P 500 is a scoreboard that tracks 500 of the biggest US companies.",
    explain: "It is a stock market index. When people say the market is up, they often mean the S&P 500 is up. Bigger companies count for more in the index than smaller ones.",
    example: "If the S&P 500 rises 1 percent in a day, the largest US companies as a group rose about 1 percent.",
    why: "It is the most common benchmark for how the US stock market is doing.", related: ["nasdaq-composite", "dow-jones", "index-fund"] },
  { slug: "nasdaq-composite", term: "Nasdaq Composite", simple: "The Nasdaq Composite tracks thousands of stocks listed on the Nasdaq, with a lot of tech companies.",
    explain: "Because many big technology companies are listed there, it tends to rise and fall with the tech industry. It is more tech heavy than the S&P 500.",
    example: "On a day when tech stocks jump, the Nasdaq Composite often outperforms other indexes.",
    why: "It is a quick read on how technology stocks are doing.", related: ["s-and-p-500", "dow-jones", "growth-stock"] },
  { slug: "dow-jones", term: "Dow Jones Industrial Average", simple: "The Dow follows 30 large, well known American companies.",
    explain: "It is one of the oldest stock market indexes. It only includes 30 companies, and it is weighted by share price, so it is a narrower view than the S&P 500.",
    example: "Companies such as Walmart and Visa have been part of the Dow.",
    why: "It is often quoted in the news as a shorthand for the market.", related: ["s-and-p-500", "nasdaq-composite", "blue-chip-stock"] },
  { slug: "blue-chip-stock", term: "Blue chip stock", simple: "A blue chip is a big, well established company with a long record of staying strong.",
    explain: "These companies usually have steady earnings, solid finances and often pay dividends. They tend to be less risky than small young companies, though they can still lose value.",
    example: "Large, long running companies in consumer goods and banking are often called blue chips.",
    why: "Blue chips are the usual starting point for people learning about stocks.", related: ["large-cap-stock", "dividend", "value-stock"] },
  { slug: "large-cap-stock", term: "Large cap stock", simple: "A large cap is a really big company worth many billions of dollars.",
    explain: "Large cap usually means a market cap of 10 billion dollars or more. These companies are well known and tend to move less than small ones.",
    example: "Apple, Microsoft and Amazon are all large cap stocks.",
    why: "Company size is a quick clue to how risky a stock might be.", related: ["market-cap", "blue-chip-stock", "growth-stock"] },
  { slug: "growth-stock", term: "Growth stock", simple: "A growth stock is a company expected to grow its sales much faster than average.",
    explain: "These companies usually put profits back into the business instead of paying dividends. Their prices can be high compared with earnings, and they can swing a lot.",
    example: "A fast growing software company that doubles sales every few years is a growth stock.",
    why: "Growth stocks can reward patience, but they often fall hard when growth slows.", related: ["value-stock", "pe-ratio", "volatility"] },
  { slug: "value-stock", term: "Value stock", simple: "A value stock looks cheap compared with how much money the company makes.",
    explain: "Value stocks often have lower P/E ratios and may pay dividends. Investors hope the market will eventually recognize their worth, but sometimes they are cheap for a good reason.",
    example: "A steady company trading at a P/E of 10 while peers trade at 20 might be called a value stock.",
    why: "Value and growth are the two classic ways of thinking about stocks.", related: ["growth-stock", "pe-ratio", "dividend"] },
  { slug: "diversification", term: "Diversification", simple: "Diversification means not putting all your eggs in one basket.",
    explain: "Spreading money across different companies, industries and types of investments means one bad outcome hurts less. It does not remove risk, but it softens it.",
    example: "Owning stocks in tech, healthcare, banking and food is more diversified than owning five tech stocks.",
    why: "It is one of the most widely repeated ideas in investing.", related: ["etf", "volatility", "index-fund"] },
  { slug: "analyst-rating", term: "Analyst rating", simple: "An analyst rating is an expert's opinion on whether a stock looks attractive.",
    explain: "Analysts at banks and research firms study companies and publish ratings like buy, hold or sell, along with a price target. They can move stocks when they change, but they can also be wrong.",
    example: "An analyst upgrades a stock from hold to buy and the price rises a few percent.",
    why: "Ratings explain many daily moves, but they are opinions, not facts.", related: ["price-target", "earnings-report", "guidance"] },
  { slug: "price-target", term: "Price target", simple: "A price target is where an analyst thinks a stock could trade in about a year.",
    explain: "It is an estimate based on the analyst's view of the company's future earnings. Targets are updated often and are frequently different from each other.",
    example: "A stock trades at 80 dollars and an analyst sets a price target of 95 dollars.",
    why: "It shows how optimistic or cautious professionals are, although it is only a guess.", related: ["analyst-rating", "eps", "pe-ratio"] },
  { slug: "ipo", term: "IPO (initial public offering)", simple: "An IPO is the first day a private company sells its shares to the public.",
    explain: "Before an IPO, a company is owned by founders and private investors. In an IPO it lists on an exchange so anyone can buy its stock. Prices can be very volatile in the first days.",
    example: "A popular app company goes public and its shares begin trading on the Nasdaq.",
    why: "IPOs are how many well known companies first become stocks you can follow.", related: ["stock-exchange", "stock-ticker", "volatility"] },
  { slug: "short-selling", term: "Short selling", simple: "Short selling is betting that a stock's price will go down.",
    explain: "A short seller borrows shares, sells them and hopes to buy them back later at a lower price. If the price rises instead, losses can be large, so it is considered high risk.",
    example: "A trader sells borrowed shares at 100 dollars, the price falls to 80 dollars and the trader buys back to profit 20 dollars per share.",
    why: "Short interest is sometimes quoted in the news and can cause sharp jumps when shorts rush to buy back.", related: ["volatility", "bear-market", "market-order"] },
];

export function findTerm(slug: string) {
  return TERMS.find((term) => term.slug === slug) ?? null;
}
