// A queue of beginner topics. The daily refresh writes the next one that has not been published yet.
export type Topic = { slug: string; title: string; angle: string };

export const TOPICS: Topic[] = [
  { slug: "what-is-inflation-and-how-does-it-affect-stocks", title: "What Is Inflation and How Does It Affect Stocks?", angle: "prices rising over time, why companies and investors care" },
  { slug: "how-do-interest-rates-affect-the-stock-market", title: "How Do Interest Rates Affect the Stock Market?", angle: "the central bank, borrowing costs, and why growth stocks react" },
  { slug: "what-is-the-federal-reserve", title: "What Is the Federal Reserve and Why Does Wall Street Watch It?", angle: "rate decisions, meetings, and market reactions" },
  { slug: "what-is-dollar-cost-averaging", title: "What Is Dollar Cost Averaging?", angle: "investing a fixed amount on a schedule instead of timing the market" },
  { slug: "how-to-research-a-stock-as-a-beginner", title: "How to Research a Stock as a Beginner", angle: "a simple checklist: business, growth, profit, risks, valuation" },
  { slug: "what-is-a-10k-report", title: "What Is a 10K Report? How to Read an Annual Report", angle: "the yearly filing public companies must publish and which parts to read first" },
  { slug: "what-is-a-balance-sheet", title: "What Is a Balance Sheet? Explained Simply", angle: "assets, liabilities and equity using a household example" },
  { slug: "what-is-an-income-statement", title: "What Is an Income Statement?", angle: "revenue, costs and profit from top to bottom" },
  { slug: "what-is-a-cash-flow-statement", title: "What Is a Cash Flow Statement?", angle: "where a company's cash really comes from and goes" },
  { slug: "what-is-short-interest", title: "What Is Short Interest and Why Do Traders Watch It?", angle: "bets against a stock and short squeezes" },
  { slug: "what-is-a-short-squeeze", title: "What Is a Short Squeeze?", angle: "how a rising price forces short sellers to buy back" },
  { slug: "what-is-market-sentiment", title: "What Is Market Sentiment?", angle: "fear and greed, and how mood moves prices" },
  { slug: "what-is-the-vix-fear-index", title: "What Is the VIX Fear Index?", angle: "how a volatility gauge works and what a high reading means" },
  { slug: "what-is-a-recession-and-what-happens-to-stocks", title: "What Is a Recession and What Happens to Stocks?", angle: "economic slowdowns and how markets have typically behaved, without predictions" },
  { slug: "what-is-an-ipo-and-how-does-it-work", title: "What Is an IPO and How Does It Work?", angle: "going public, underwriters, the first trading day" },
  { slug: "what-is-a-spac", title: "What Is a SPAC?", angle: "blank check companies and why they are riskier" },
  { slug: "what-is-a-reit", title: "What Is a REIT? Real Estate Stocks Explained", angle: "owning property through a stock and how dividends work" },
  { slug: "what-are-penny-stocks", title: "What Are Penny Stocks and Why Are They Risky?", angle: "low priced stocks, thin trading and scams to avoid" },
  { slug: "what-is-after-hours-trading", title: "What Is After Hours Trading?", angle: "extended sessions, thin volume and big earnings moves" },
  { slug: "what-is-premarket-trading", title: "What Is Premarket Trading?", angle: "trading before the opening bell and what premarket moves mean" },
  { slug: "what-is-a-stock-split-and-should-you-care", title: "What Is a Stock Split and Should You Care?", angle: "more shares at a lower price, nothing changes in value" },
  { slug: "what-is-a-dividend-reinvestment-plan", title: "What Is a Dividend Reinvestment Plan?", angle: "using dividends to buy more shares automatically" },
  { slug: "what-is-compound-growth", title: "What Is Compound Growth and Why Does Time Matter?", angle: "growth on growth with a plain numeric example" },
  { slug: "what-is-the-difference-between-investing-and-trading", title: "Investing vs Trading: What Is the Difference?", angle: "time horizon, effort and risk" },
  { slug: "what-is-a-bear-market-rally", title: "What Is a Bear Market Rally?", angle: "short rebounds inside a falling market" },
  { slug: "what-is-a-stock-buyback", title: "What Is a Stock Buyback and Why Do Companies Do It?", angle: "fewer shares outstanding and earnings per share" },
  { slug: "what-does-overvalued-and-undervalued-mean", title: "What Does Overvalued and Undervalued Mean?", angle: "price versus worth and why people disagree" },
  { slug: "what-is-a-moat-in-investing", title: "What Is an Economic Moat?", angle: "lasting competitive advantages with everyday examples" },
  { slug: "what-is-market-capitalization-large-mid-small", title: "Large Cap vs Mid Cap vs Small Cap Stocks", angle: "company size categories and typical differences" },
  { slug: "what-is-a-mutual-fund", title: "What Is a Mutual Fund and How Is It Different From an ETF?", angle: "pooled money, pricing once a day and fees" },
  { slug: "what-is-an-expense-ratio", title: "What Is an Expense Ratio?", angle: "the yearly fee on funds and why small differences add up" },
  { slug: "what-is-a-brokerage-account", title: "What Is a Brokerage Account?", angle: "how people buy stocks, account types and what to compare" },
  { slug: "what-is-a-roth-ira", title: "What Is a Roth IRA? A Beginner Explanation", angle: "tax advantaged retirement accounts at a high level, not tax advice" },
  { slug: "what-is-fractional-share-investing", title: "What Are Fractional Shares?", angle: "buying a slice of an expensive stock" },
  { slug: "what-is-an-earnings-call", title: "What Is an Earnings Call and What Should You Listen For?", angle: "management commentary, guidance and analyst questions" },
  { slug: "what-is-forward-guidance", title: "What Is Forward Guidance in Earnings?", angle: "company outlooks and why they move stocks" },
  { slug: "what-is-an-analyst-upgrade-or-downgrade", title: "What Is an Analyst Upgrade or Downgrade?", angle: "ratings changes and why the stock reacts" },
  { slug: "what-is-insider-trading-and-insider-buying", title: "What Is Insider Buying and Selling?", angle: "legal insider transactions versus illegal insider trading" },
  { slug: "what-is-a-supply-chain-and-why-it-moves-stocks", title: "What Is a Supply Chain and Why Does It Move Stocks?", angle: "shortages, shipping, and company costs" },
  { slug: "what-are-tariffs-and-how-do-they-affect-stocks", title: "What Are Tariffs and How Do They Affect Stocks?", angle: "taxes on imports and winners and losers" },
  { slug: "what-is-gdp-and-why-does-it-matter-to-investors", title: "What Is GDP and Why Does It Matter to Investors?", angle: "the size of the economy and growth reports" },
  { slug: "what-is-the-jobs-report", title: "What Is the Jobs Report and Why Does It Move the Market?", angle: "employment data released monthly and rate expectations" },
  { slug: "what-is-cpi-and-the-inflation-report", title: "What Is the CPI Inflation Report?", angle: "how inflation is measured and the market reaction" },
  { slug: "what-is-quantitative-tightening", title: "What Is Quantitative Tightening?", angle: "the central bank shrinking its balance sheet, in simple terms" },
  { slug: "what-is-the-yield-curve", title: "What Is the Yield Curve and What Is an Inverted Yield Curve?", angle: "bond yields and why people watch the shape" },
  { slug: "what-are-treasury-bonds", title: "What Are Treasury Bonds and How Do They Affect Stocks?", angle: "government bonds, yields and the choice between bonds and stocks" },
  { slug: "what-is-an-index-rebalance", title: "What Is an Index Rebalance and Why Do Stocks Jump When Added to the S&P 500?", angle: "index inclusion and fund buying" },
  { slug: "how-the-s-and-p-500-is-built", title: "How Is the S&P 500 Built and Who Decides What Is In It?", angle: "market cap weighting and selection rules" },
  { slug: "what-is-an-ai-stock", title: "What Is an AI Stock? How Companies Make Money From Artificial Intelligence", angle: "chips, cloud, software and what to watch, without hype" },
  { slug: "what-are-semiconductor-stocks", title: "What Are Semiconductor Stocks?", angle: "chip designers, makers and equipment companies and the cycle" },
  { slug: "what-are-bank-stocks-and-how-do-banks-make-money", title: "How Do Banks Make Money? Bank Stocks Explained", angle: "net interest margin, fees and credit losses" },
  { slug: "what-are-defensive-stocks", title: "What Are Defensive Stocks?", angle: "steady demand businesses and why people hold them in slowdowns" },
  { slug: "what-are-cyclical-stocks", title: "What Are Cyclical Stocks?", angle: "businesses that follow the economy" },
  { slug: "what-are-dividend-aristocrats", title: "What Are Dividend Aristocrats?", angle: "companies that raise dividends year after year" },
  { slug: "what-is-a-price-to-sales-ratio", title: "What Is the Price to Sales Ratio?", angle: "valuing companies that are not yet profitable" },
  { slug: "what-is-return-on-equity", title: "What Is Return on Equity?", angle: "profit relative to shareholder money" },
  { slug: "what-is-debt-to-equity-ratio", title: "What Is the Debt to Equity Ratio?", angle: "how much a company borrows relative to what it owns" },
  { slug: "what-is-free-cash-flow-yield", title: "What Is Free Cash Flow Yield?", angle: "cash generated compared with company value" },
  { slug: "what-is-a-stock-screener", title: "What Is a Stock Screener and How Do You Use One?", angle: "filtering thousands of stocks by simple rules" },
  { slug: "how-to-read-a-stock-chart", title: "How to Read a Stock Chart for Beginners", angle: "line and candle charts, trend, support and resistance explained simply" },
  { slug: "what-is-a-moving-average", title: "What Is a Moving Average?", angle: "smoothing price over time and the 50 day and 200 day lines" },
  { slug: "what-is-risk-tolerance", title: "What Is Risk Tolerance?", angle: "how much a drop you can handle and why it shapes choices" },
];
